server:
  port: 9001

#spring-hibernate for mysql
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  #connection MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/db_selling?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456789



